//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Arts/LotsOfMiles/InputSystem/IA_LotsOfMiles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @IA_LotsOfMiles: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @IA_LotsOfMiles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""IA_LotsOfMiles"",
    ""maps"": [
        {
            ""name"": ""LotsOfMiles"",
            ""id"": ""c195b271-ec12-4915-900d-0cd32d476fb7"",
            ""actions"": [
                {
                    ""name"": ""SingleTouch"",
                    ""type"": ""Button"",
                    ""id"": ""880544c7-f7d8-4654-94b8-89568f7bbc42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9a086a1f-2ca6-4b0a-b4c2-6074a40183ce"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SingleTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LotsOfMiles
        m_LotsOfMiles = asset.FindActionMap("LotsOfMiles", throwIfNotFound: true);
        m_LotsOfMiles_SingleTouch = m_LotsOfMiles.FindAction("SingleTouch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LotsOfMiles
    private readonly InputActionMap m_LotsOfMiles;
    private List<ILotsOfMilesActions> m_LotsOfMilesActionsCallbackInterfaces = new List<ILotsOfMilesActions>();
    private readonly InputAction m_LotsOfMiles_SingleTouch;
    public struct LotsOfMilesActions
    {
        private @IA_LotsOfMiles m_Wrapper;
        public LotsOfMilesActions(@IA_LotsOfMiles wrapper) { m_Wrapper = wrapper; }
        public InputAction @SingleTouch => m_Wrapper.m_LotsOfMiles_SingleTouch;
        public InputActionMap Get() { return m_Wrapper.m_LotsOfMiles; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LotsOfMilesActions set) { return set.Get(); }
        public void AddCallbacks(ILotsOfMilesActions instance)
        {
            if (instance == null || m_Wrapper.m_LotsOfMilesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LotsOfMilesActionsCallbackInterfaces.Add(instance);
            @SingleTouch.started += instance.OnSingleTouch;
            @SingleTouch.performed += instance.OnSingleTouch;
            @SingleTouch.canceled += instance.OnSingleTouch;
        }

        private void UnregisterCallbacks(ILotsOfMilesActions instance)
        {
            @SingleTouch.started -= instance.OnSingleTouch;
            @SingleTouch.performed -= instance.OnSingleTouch;
            @SingleTouch.canceled -= instance.OnSingleTouch;
        }

        public void RemoveCallbacks(ILotsOfMilesActions instance)
        {
            if (m_Wrapper.m_LotsOfMilesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILotsOfMilesActions instance)
        {
            foreach (var item in m_Wrapper.m_LotsOfMilesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LotsOfMilesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LotsOfMilesActions @LotsOfMiles => new LotsOfMilesActions(this);
    public interface ILotsOfMilesActions
    {
        void OnSingleTouch(InputAction.CallbackContext context);
    }
}
